baseURL = 'https://ideastone.pages.dev/'
languageCode = 'en-us'
title = 'Ideastone â›°ï¸'
theme = 'paper'
paginate = 5
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true
mainsections = ["posts", "papermod"]

[minify]
disableXML = true

[languages.en]
languageName = "English"
weight = 1

[languages.en.taxonomies]
category = "categories"
tag = "tags"
series = "series"

[[languages.en.menu.main]]
name = "Archive"
url = "archives"
weight = 5

[[languages.en.menu.main]]
name = "Search"
url = "search/"
weight = 10

[[languages.en.menu.main]]
name = "Tags"
url = "tags/"
weight = 10

[[languages.en.menu.main]]
name = "About"
url = "about/"
weight = 10

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
env = "production"
description = "building something"
author = "ideastone"
defaultTheme = "auto"
# å¸–å­åº•éƒ¨çš„åˆ†äº«æŒ‰é’®
ShowShareButtons = false
ShowReadingTime = true
displayFullLangName = true
# å¸–å­ä¸‹æ–¹çš„ä¸‹ä¸€ç¯‡
ShowPostNavLinks = true
# å¸–å­çš„é¢åŒ…å±‘å¯¼èˆª
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowAllPagesInArchive = true
ShowPageNums = true
ShowToc = true
images = ["images/"]

[params.profileMode]
enabled = false
title = "Ideastone â›°ï¸"
imageUrl = "#"
imageTitle = "my image"

[[params.profileMode.buttons]]
name = "Archives"
url = "archives"

[[params.profileMode.buttons]]
name = "Tags"
url = "tags"

[params.homeInfoParams]
Title = "Idea stone happy ğŸˆ"
Content = """


"""

[[params.socialIcons]]
name = "github"
title = "Github"
url = "https://github.com/anotcat"

[[params.socialIcons]]
name = "X"
title = "Twitter"
url = "https://x.com/anotcat"

[[params.socialIcons]]
name = "KoFi"
title = "Buy me a Ko-Fi :)"
url = "https://ko-fi.com/anotcat"

# å¸–å­æ˜¾ç¤ºç¼–è¾‘é“¾æ¥
[params.editPost]
URL = "https://github.com/anotcat/ideastone/tree/main/content"
Text = "suggest"
appendFilePath = true

[params.assets]
disableHLJS = true
# faviconåœ¨assetsæ–‡ä»¶å¤¹ä¸‹
favicon = "favicon.svg"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true
